
@BaseAddress = https://richillcapital-exchange-api.azurewebsites.net
@Localhost = https://localhost:10000
@Route = api/accounts

@accountId = ad109997-35e1-44a8-8796-39bfe829ab53

### Create Account
POST {{Localhost}}/{{Route}}
Content-Type: application/json

{
  "name": "Test d",
  "positionMode": "Hedging",
  "currency": "TWD",
  "initialDeposit": 100000
}

### Create Account Order
POST {{Localhost}}/{{Route}}/{{accountId}}/orders
Content-Type: application/json

{
  "tradeType": "Buy",
  "quantity": 60,
  "symbol": "AAPL",
  "orderType": "Market",
  "timeInForce": "IOC"
}

### List Acounts
GET {{Localhost}}/{{Route}}

### Get Account by Id
GET {{Localhost}}/{{Route}}/{{accountId}}

### Get Account Orders
GET {{Localhost}}/{{Route}}/{{accountId}}/orders

### Get Account Executions
GET {{Localhost}}/{{Route}}/{{accountId}}/executions

### Get Account Positions
GET {{Localhost}}/{{Route}}/{{accountId}}/positions

### Get Account Trades
GET {{Localhost}}/{{Route}}/{{accountId}}/trades

### Get Account Performance
GET {{Localhost}}/{{Route}}/{{accountId}}/performance