
@BaseAddress = https://richillcapital-exchange-api.azurewebsites.net
@Localhost = https://localhost:10000
@Route = api/accounts

@accountId = 513229cc-4dc4-45dd-901b-1e283bafa6ac

### List Acounts
GET {{Localhost}}/{{Route}}

### Get Account by Id
GET {{Localhost}}/{{Route}}/{{accountId}}

### Create Account
POST {{Localhost}}/{{Route}}
Content-Type: application/json

{
  "name": "Test Account",
  "currency": "TWD",
  "initialDeposit": 100000
}

### Get Account Orders
GET {{Localhost}}/{{Route}}/{{accountId}}/orders

### Get Account Executions
GET {{Localhost}}/{{Route}}/{{accountId}}/executions

### Get Account Positions
GET {{Localhost}}/{{Route}}/{{accountId}}/positions

### Get Account Trades
GET {{Localhost}}/{{Route}}/{{accountId}}/trades