
@BaseAddress = https://richillcapital-exchange-api.azurewebsites.net
@Localhost = https://localhost:10000
@Route = api/bots
@botId = test-33

### Create Bot
POST {{Localhost}}/{{Route}}
Content-Type: application/json

{
    "id": "test-33",
    "name": "test-33",
    "description": "Test http file",
    "platform": "MetaTrader5"
}

### List Bots
GET {{Localhost}}/{{Route}}

### Emit signal 
POST {{Localhost}}/{{Route}}/{{botId}}/signals
Content-Type: application/json

{
    "time": "2021-01-01T00:12:02Z",
    "tradeType": "Buy",
    "symbol": "EURUSD",
    "volume": 0,
    "price": 0
}

### List Trading Signals
GET {{Localhost}}/{{Route}}/{{botId}}/signals